<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projetos IFBA Login</title>
    <link rel="stylesheet" href="/css/home.css">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
</head>
<body>
     <header>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4caf50">
       <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto"> 
        <li class="nav-item mx-2">
            <a class="nav-link active" href="/home">
                <i class="bi bi-house-door me-1"></i>Página Inicial
            </a>
        </li>
        <li class="nav-item mx-2">
            <a class="nav-link" href="/questionario">
                <i class="bi bi-clipboard2-data me-1"></i>Questionário
            </a>
        </li>
        <li class="nav-item mx-2">
            <a class="nav-link" href="/relatorios">
                <i class="bi bi-graph-up me-1"></i>Relatórios
            </a>
        </li>
    </ul>
</div>
    </nav>
</header>
    <section id="busca">
        <h2>Pesquisar</h2>
        <form>
            <input type="text" id="campo-busca" placeholder="Pesquisar...">
            <button type="submit">Buscar</button>
        </form>
    </section>

    <section id="projetos">
        <h2>Projetos</h2>
        <div class="projetos">
            <!--Lista de Projetos-->

        </div>
    </section>

    <!--Teste-->
    <a href="/questionario">Ficha para análise de (in)segurança alimentar</a>
   
    
    <footer>
        <p> &copy; 2025 Projetos IFBA</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>