<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projetos IFBA Login</title>
    <link rel="stylesheet" href="/css/home.css">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="">Página Inicial</a></li>
                <li class="btnRelatorio"><a href="/relatorio.jte">Relatorios</a></li>
                
            </ul>
        </nav>
    </header>
    <section id="busca">
        <h2>Pesquisar</h2>
        <form>
            <input type="text" id="campo-busca" placeholder="Pesquisar...">
            <button type="submit">Buscar</button>
        </form>
    </section>

    <section id="projetos">
        <h2>Projetos</h2>
        <div class="projetos">
            <!--Lista de Projetos-->

        </div>
    </section>

    <!--Teste-->
    <a href="/questionario">Ficha para análise de (in)segurança alimentar</a>
   
    
    <footer>
        <p> &copy; 2025 Projetos IFBA</p>
    </footer>
</body>
</html>